apiVersion: v1
kind: Pod
metadata: 
    name: eks-b1-pod
    labels: 
      env: uat-env
      app: eb-ms-app
    namespace: prod
spec: 
  containers:
    - name: eks-b1-nginx-instance
      image: nginx
      ports:
        - name: http
          containerPort: 80
    - name: eb-ms-tomcat-instance
      image: tomcat
      ports:
        - name: java
          containerPort: 8080