---
# copying svc-manifest.yml file
# svc-manifest for NodePort
apiVersion: v1
kind: Service
metadata:
  name: eks-svc
  labels:
    env: uat-env
    app: eb-ms-app 
  namespace: prod #<ns-name>
spec:
  type: NodePort
  selector:
    app: eb-ms-app #[app: eb-ms-app]
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: http-tomcat
      protocol: TCP
      port: 8080
      targetPort: 8080
...